version: '3.3'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: customer_purchases
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
  server:
    build: '.'
    ports:
      - "8080:8080"
