# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict, Optional  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UploadResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, number_of_rows_stored: int=None, number_of_error_rows: int=None):  # noqa: E501
        """UploadResponse - a model defined in Swagger

        :param number_of_rows_stored: The number_of_rows_stored of this UploadResponse.  # noqa: E501
        :type number_of_rows_stored: int
        :param number_of_error_rows: The number_of_error_rows of this UploadResponse.  # noqa: E501
        :type number_of_error_rows: int
        """
        self.swagger_types = {
            'number_of_rows_stored': int,
            'number_of_error_rows': int
        }

        self.attribute_map = {
            'number_of_rows_stored': 'numberOfRowsStored',
            'number_of_error_rows': 'numberOfErrorRows'
        }

        self._number_of_rows_stored = number_of_rows_stored
        self._number_of_error_rows = number_of_error_rows

    @classmethod
    def from_dict(cls, dikt) -> 'UploadResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UploadResponse of this UploadResponse.  # noqa: E501
        :rtype: UploadResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def number_of_rows_stored(self) -> Optional[int]:
        """Gets the number_of_rows_stored of this UploadResponse.


        :return: The number_of_rows_stored of this UploadResponse.
        :rtype: int
        """
        return self._number_of_rows_stored

    @number_of_rows_stored.setter
    def number_of_rows_stored(self, number_of_rows_stored: int):
        """Sets the number_of_rows_stored of this UploadResponse.


        :param number_of_rows_stored: The number_of_rows_stored of this UploadResponse.
        :type number_of_rows_stored: int
        """

        self._number_of_rows_stored = number_of_rows_stored

    @property
    def number_of_error_rows(self) -> Optional[int]:
        """Gets the number_of_error_rows of this UploadResponse.


        :return: The number_of_error_rows of this UploadResponse.
        :rtype: int
        """
        return self._number_of_error_rows

    @number_of_error_rows.setter
    def number_of_error_rows(self, number_of_error_rows: int):
        """Sets the number_of_error_rows of this UploadResponse.


        :param number_of_error_rows: The number_of_error_rows of this UploadResponse.
        :type number_of_error_rows: int
        """

        self._number_of_error_rows = number_of_error_rows
